# OpenGewe配置文件
[gewe_apps]
# 默认设备配置
[gewe_apps.1]
name = "默认设备"
# 使用geweapi需传值http://www.geweapi.com/gewe/v2/api，或gewe临时提供的ip+端口地址
# 当前geweapi管理后台中提供的base_url可能为http://218.78.116.24:10884/gewe/v2/api
base_url = "http://218.78.116.24:10884/gewe/v2/api"
download_url = ""                                   # 使用geweapi无需传值，私有化部署则根据部署的镜像地址和端口来填写
callback_url = ""                                   # 使用geweapi无需传值，而是在geweapi后台中设置，私有化部署则根据部署的后端回调服务填写回调地址
app_id = "wx_12345ABCdeFGhi6789"                    # 设备id，在geweapi的管理后台内扫码登录创建设备时生成
token = "1234abcd-1234-1234-1234-1234abcd1234"      # geweapi平台分配的token
is_gewe = true                                      # 是否使用geweapi，设置为false则切换至私有化部署

# 设备2示例配置
[gewe_apps.2]
name = "设备2"
base_url = "http://www.geweapi.com/gewe/v2/api"
download_url = ""
callback_url = "http://yourserver.com/callbacks/device2"
app_id = "wx_another_device_id"
token = "another-token-value"
is_gewe = true

# 设备3示例配置 - 私有化部署
[gewe_apps.3]
name = "设备3-私有化部署"
base_url = "http://192.168.1.100:8080/gewe/v2/api"
download_url = "http://192.168.1.100:8080/download"
callback_url = "http://yourserver.com/callbacks/device3"
app_id = "wx_private_device_id"
token = "private-token-value"
is_gewe = false

[plugins]
plugins_dir = "plugins"             # 插件目录
enabled_plugins = ["ExamplePlugin"] # 全局启用的插件列表，全局启用则全部设备都会加载并启用该插件
disabled_plugins = []               # 全局禁用的插件列表，全局禁用则不会加载

[queue]
queue_type = "simple" # 消息队列类型，可选值为"simple"或"advanced"
# 以下配置仅当queue_type设为advanced时有效
broker = "redis://localhost:6379/0"  # 消息队列后端连接URI，可用redis或rabbitmq
backend = "redis://localhost:6379/0" # 消息队列结果存储URI
name = "opengewe_messages"           # 队列名称
concurrency = 4                      # worker并发数量

[logging]
level = "INFO"        # 日志级别: TRACE, DEBUG, INFO, SUCCESS, WARNING, ERROR, CRITICAL
format = "color"      # 日志格式: "color", "json", "simple"
rotation = "500 MB"   # 日志轮换大小
retention = "10 days" # 日志保留时间
compression = "zip"   # 日志压缩格式
path = "./logs"       # 日志路径
stdout = true         # 是否输出到控制台

[webpanel]
# WebPanel后台管理配置
secret_key = "your-super-secret-key-change-this-in-production-environment-12345"
debug = true
host = "0.0.0.0"
port = 5432
admin_username = "admin"
admin_password = "admin@123"

# 数据库配置 - 仅支持MySQL（需要schema支持）
[webpanel.database]
type = "mysql"                 # 仅支持 mysql
host = "localhost"             # 数据库主机
port = 3306                    # 数据库端口
username = "opengewe"          # 数据库用户名
password = "opengewe123"       # 数据库密码
database = "opengewe_webpanel" # 数据库名称
echo_sql = false               # 是否在控制台打印SQL语句（调试用）

# Redis配置
[webpanel.redis]
host = "localhost"
port = 6379
db = 0
# 如果需要密码，取消注释下面一行
# password = "your_redis_password"
